theme = 'relearn'

baseURL = "https://io.midori-ai.xyz/"
title = "Midori-AI"

canonifyURLs = false # true -> all relative URLs would instead be canonicalized using baseURL
relativeURLs = false # true -> rewrite all relative URLs to be relative to the current content
uglyURLs = false     # true -> basic/index.html -> basic.html
enableRobotsTXT = true

disableHugoGeneratorInject = false

[outputs]
  # add JSON to the home to support Lunr search; This is a mandatory setting
  # for the search functionality
  # add PRINT to home, section and page to activate the feature to print whole
  # chapters
  home = ["HTML", "RSS", "PRINT", "SEARCH", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[markup]
  [markup.highlight]
    # if `guessSyntax = true`, there will be no unstyled code even if no language
    # was given BUT Mermaid and Math codefences will not work anymore! So this is a
    # mandatory setting for your site if you want to use Mermaid or Math codefences
    guessSyntax = true

    # here in this showcase we use our own modified chroma syntax highlightning style
    # which is imported in theme-relearn-light.css / theme-relearn-dark.css;
    # if you want to use a predefined style instead:
    # - remove the following `noClasses`
    # - set the following `style` to a predefined style name
    # - remove the `@import` of the self-defined chroma stylesheet from your CSS files
    #   (here eg.: theme-relearn-light.css / theme-relearn-dark.css)
    noClasses = false
    style = "tango"

  [markup.goldmark.renderer]
    # activated for this showcase to use HTML and JavaScript; decide on your own needs;
    # if in doubt, remove this line
    unsafe = true

[params]
  description = "Documentation for Midori-AI"
  author = "Luna Midori"
  showVisitedLinks = false
  collapsibleMenu = true
  disableBreadcrumb = false
  disableInlineCopyToClipBoard = true
  disableNextPrev = false
  disableLandingPageButton = true
  breadcrumbSeparator = "->"
  disableRootBreadcrumb = false
  disableTermBreadcrumbs = false
  titleSeparator = "::"
  themeVariant = [ "auto", "relearn-bright", "relearn-light", "relearn-dark", "learn", "neon", "blue", "green", "red" ]
  themeVariantAuto = [ "relearn-light", "relearn-dark" ]
  disableSeoHiddenPages = true
  additionalContentLanguage = [ "en" ]
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  mermaidZoom = true
  alwaysopen = true
